spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/springdatajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

decorator:
  datasource:
    p6spy:
      enable-logging: true